server:
  port : 8080
app:
  datasource:
    coredb:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/coredb?createDatabaseIfNotExist=true
      username: root
      password: 111111
      hikari:
        connection-timeout: 5000
        maximum-pool-size: 10
    sitedb:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sitedb?createDatabaseIfNotExist=true
      username: root
      password: 111111
      hikari:
        connection-timeout: 5000
        maximum-pool-size: 10
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        hbm2ddl: validate
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect